# Generated by Django 3.2.8 on 2021-10-18 00:17

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Address',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('country', models.CharField(max_length=25)),
                ('state', models.CharField(max_length=25)),
                ('city', models.CharField(max_length=25)),
                ('postal_code', models.CharField(blank=True, max_length=25)),
                ('line_1', models.CharField(max_length=1000, verbose_name='Address line 1')),
                ('line_2', models.CharField(blank=True, max_length=1000, verbose_name='Address line 2')),
                ('line_3', models.CharField(blank=True, max_length=1000, verbose_name='Address line 3')),
            ],
        ),
    ]
